spring.profiles.active=dev

spring.application.name=CharityWeb
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/charity_web
spring.datasource.username=root
spring.datasource.password=@Ftwsdsadoe8h
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# VNPay Configurations
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/v1/payments/callback
vnpay.tmnCode=YourVnPayTmnCodeHere
vnpay.hashSecret=YourVnPayHashSecretHere

# JWT Configuration
app.jwt.secret=YourSuperSecretKeyForJwtGenerationMakeItLongAndSecure!
app.jwt.expiration=86400000
app.jwt.refreshExpiration=604800000

# File Upload Configuration
app.upload.dir=uploads/

spring.devtools.restart.enabled=false
spring.devtools.restart.exclude=static/**,public/**,templates/**